services:
  speech-to-text-backend:
    build: .
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - DEEPGRAM_API_KEY=${DEEPGRAM_API_KEY}
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "https://api-backend.chatess.com/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - speech-network

networks:
  speech-network:
    driver: bridge
